---

- name: Checking if Harbor is already installed
  stat:
    path: "{{ harbor_install_dir }}/harbor/common/config"
  register: harbor_folder_st

- name: do facts module to get latest information
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter

- include_tasks: install.yml
- include_tasks: configure.yml

# Restart only if we changed the registry realm
- include_tasks: restart.yaml
  when: harbor_behind_proxy is defined and harbor_behind_proxy and harbor_registry_realm_protocol != harbor_ui_url_protocol

- include_tasks: create_users.yml
- include_tasks: create_projects.yml

- name: remove install package
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/harbor.tgz
    - "{{ harbor_install_dir }}/harbor/harbor.v{{ harbor_version }}.tar.gz"

- include_tasks: service.yml
